### ISSUE TITLE
Finetune on face recognition with resolution@224 problem by using EfficientNet-b0?

### ISSUE THREAD

**Issue by yeluyue** [lukemelas/EfficientNet-PyTorch#41] opened 2019-06-27 02:10 UTC
Hi, I trained EfficientNet-b0 for face recognition task by using the Msceleb-1M. The classnum in my experiment is 512. However,  the output of the last layer is always Nan just from the first iteration. Is it different between object classification  task and face recognition task on EfficientNet ?

**Comment by Catosine** [comment] 2019-06-27 12:02
Hi @yeluyue ! I'm also working on transferring EfficientNet-b0 to MS1M-Celeb. However, I'm using 1k-people set for my experiment.
In general, face identification has no difference compared with object recognition, for the algorithm won't know if you are sending it a human face or just a car.
As for your situation, I guess there might be something wrong with your code, for example, the data preprocessing.
GL,

**Comment by Catosine** [comment] 2019-06-29 04:19
Quick update: EfficientNet-b0 with cleaned 1k-people data has an result of valid top1 88.83 and top5 of 96.02. This is caused by b0 is not deep enough.

**Comment by lukemelas** [comment] 2019-06-29 16:18
Thanks for the update!

**Comment by lukemelas** [comment] 2019-06-30 00:01
Just wanted to say that now with #44, it is a lot easier to use a model with a different number of classes: 
```
model = EfficientNet.from_pretrained('efficientnet-b1', num_classes=512)
```

**Comment by lukemelas** [comment] 2019-06-30 00:01
Also, let me know if this is still an open issue or if it can be closed.

**Comment by Catosine** [comment] 2019-06-30 00:20
Dope you actually add a control variables for different classes! That is what I really need now! Thanks man:)
BTW I think it is definitely okay to close this issue.
Thanks again for your amazing work!

**Closed** 2019-07-01 02:16 UTC

**Comment by lukemelas** [comment] 2019-07-01 05:26
Thank you so much for the reply! I am really happy to hear you are enjoying the repo!
